name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: install build dependencies
        run: |
          pip install --upgrade setuptools wheel twine build

      - name: Build and publish
        run: |
          python -m build
          python -m twine upload -u __token__ -p ${{ secrets.PYPI_API_TOKEN }} dist/*
